ALTER TABLE vehicles DROP INDEX `PRIMARY`;
ALTER TABLE `vehicles` ADD `hash` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`hash`);
ALTER TABLE `vehicles` CHANGE `hash` `hash` INT(11) NOT NULL;
